# Generated by Django 2.1.1 on 2018-09-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div', '0002_remove_sendrequest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendrequest',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='replyrequest',
            name='date',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='replyrequest',
            name='retime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sendrequest',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
