# Generated by Django 2.1.1 on 2018-09-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div', '0003_auto_20180916_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiverequest',
            old_name='tname',
            new_name='tuname',
        ),
    ]
