# Generated by Django 2.1.1 on 2018-09-16 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div', '0004_auto_20180916_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiverequest',
            name='rrid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div.SendRequest'),
        ),
        migrations.AlterField(
            model_name='replyrequest',
            name='rerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div.SendRequest'),
        ),
    ]
