# Generated by Django 2.1.1 on 2018-09-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div', '0005_auto_20180916_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replyrequest',
            old_name='date',
            new_name='redate',
        ),
    ]
