# Generated by Django 2.1.1 on 2018-09-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div', '0007_auto_20180918_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyrequest',
            name='retime',
            field=models.TimeField(auto_now=True),
        ),
    ]
