# Generated by Django 2.1.1 on 2018-09-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div', '0008_auto_20180918_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyrequest',
            name='retime',
            field=models.DateField(auto_now=True),
        ),
    ]
